### ISSUE TITLE
Default user group is arbitrary set to the lowest accessible uid

### ISSUE THREAD

**Issue by xperseguers** [IchHabRecht/begroups_roles#17]
The way the default user group is chosen at startup is wrong as it is based on the lowest role's uid instead of the first role ordered by title. The list of available roles is properly sorted by title but the default makes no sense that way.

**Comment by IchHabRecht** [comment]
Hi @xperseguers,

Thank you for your information. IMHO the default role cannot be the first one sorted by alphabet. It should be the first role that is found in the subgroup ordering. I will check if this is broken. Would you mind to recheck your installation if the first group (marked as role) is taken for your user by default?
