### ISSUE TITLE
Option to disallow "All Groups" selection

### ISSUE THREAD

**Issue by baschny** [IchHabRecht/begroups_roles#5]
In some use-cases we might want to enforce the user to choose one of the groups as the "All Groups" option is confusing for this editor (too many mount points etc).

So upon login the first group is chosen as the current role and the user can then choose any of the other groups.

It would be cool to have an option to enable this behaviour. Implementation should be fairly easy in the Hook and Icon toolbar rendering.

Thanks for keeping this extension up to date with the TYPO3 versions, @IchHabRecht!

**Comment by IchHabRecht** [comment]
Hi Ernesto,

Thanks for your request. As I find this one really helpful, would you mind to test the current patch at https://github.com/IchHabRecht/begroups_roles/tree/add-group-limit

Thank you very much.
